version: "3"

services:
  db:
    image: mysql:5
    container_name: music_db
    env_file: .env
    volumes:
      - data:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - "3306:3306"

  volumes:
    data: